{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Company": "Boston Scientific", "StoreID": null, "Site_Store_Facility Name": "Boston Scientific - Quincy Location", "Type of Facility": null, "Fac_simple": null, "Street Address": "500 Commander Shea Boulevard", "City": "Quincy", "State": "MA", "Zip": "2171", "OnlineDate": null, "Capacity": "1200", "System Mounting": null, "NEM": null, "Solar Installer Company": null, "Solar System Owner": null, "Facility Owner": null, "Facility Tenant": null, "Notes": null, "New": 0, "LocationGeo": "500 Commander Shea Boulevard Quincy, MA", "Latitude": 42.296829, "Longitude": -71.031372, "Confidence": "High", "AddyCheck": "500 Commander Shea Boulevard Quincy, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.03137207, 42.29682922 ] } },
{ "type": "Feature", "properties": { "Company": "FedEx", "StoreID": null, "Site_Store_Facility Name": "FedEx Ground Natick, MA", "Type of Facility": "Distribution", "Fac_simple": "Distribution", "Street Address": "30 Superior Dr", "City": "Natick", "State": "MA", "Zip": "1760", "OnlineDate": "11\/1\/2015", "Capacity": "395", "System Mounting": "Roof", "NEM": "Yes", "Solar Installer Company": "SoCore", "Solar System Owner": "SoCore", "Facility Owner": "Private Company", "Facility Tenant": "Private Company", "Notes": "This site is mechanically complete, AHJ inspection in progress. Online prior to 11\/16\/15", "New": 1, "LocationGeo": "30 Superior Dr Natick, MA", "Latitude": 42.304302, "Longitude": -71.375755, "Confidence": "High", "AddyCheck": "30 Superior Dr Natick, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.37575531, 42.30430222 ] } },
{ "type": "Feature", "properties": { "Company": "IKEA", "StoreID": null, "Site_Store_Facility Name": "IKEA Stoughton", "Type of Facility": "Retail", "Fac_simple": "Retail", "Street Address": "1 IKEA Way", "City": "Stoughton", "State": "MA", "Zip": "2072", "OnlineDate": "5\/8\/2013", "Capacity": "909", "System Mounting": "roof", "NEM": "Yes", "Solar Installer Company": "REC Solar", "Solar System Owner": "IKEA", "Facility Owner": "IKEA ", "Facility Tenant": "IKEA", "Notes": "Reflects expansion by 318-kW in 04\/2015", "New": 0, "LocationGeo": "1 IKEA Way Stoughton, MA", "Latitude": 42.137581, "Longitude": -71.068550, "Confidence": "High", "AddyCheck": "1 IKEA Way Stoughton, MA" }, "geometry": { "type": "Point", "coordinates": [ -71.06855011, 42.13758087 ] } }
  ]
}